import { Merchant, Product } from "@/types";

export const DEMO_MERCHANTS: (Merchant & { initialProducts: Product[] })[] = [
  // 1. ErgoSpace (Flagship Ergonomic Furniture)
  {
    id: "ergospace",
    name: "ErgoSpace",
    description: "Premium ergonomic task seating, dynamic active lumbar systems, and modular ergonomic accessories.",
    categories: ["Seating", "Desks", "Accessories"],
    maxDiscountPercent: 15,
    minimumMarginPercent: 20,
    maxAutoTransactionAmount: 15000,
    approvalRequiredAbove: 12000,
    allowSlowMovingInventoryDiscount: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    initialProducts: [
      {
        id: "prod-101",
        merchantId: "ergospace",
        name: "ErgoChair Lite",
        description: "Breathable mesh ergonomic task chair with dynamic lumbar support.",
        category: "Seating",
        price: 1199,
        stock: 25,
        attributes: { color: "Black", weightCapacityKg: 110, warrantyYears: 2 },
        deliveryDays: 3,
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "prod-102",
        merchantId: "ergospace",
        name: "ErgoChair Pro",
        description: "Advanced ergonomic office chair with 4D armrests and headrest.",
        category: "Seating",
        price: 2499,
        stock: 12,
        attributes: { color: "Slate Gray", weightCapacityKg: 136, warrantyYears: 5 },
        deliveryDays: 4,
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "prod-103",
        merchantId: "ergospace",
        name: "ErgoChair Executive",
        description: "Premium leather ergonomic executive chair with adaptive synchro-tilt.",
        category: "Seating",
        price: 3999,
        stock: 6,
        attributes: { color: "Midnight Leather", weightCapacityKg: 150, warrantyYears: 7 },
        deliveryDays: 5,
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "prod-104",
        merchantId: "ergospace",
        name: "Lumbar Support Cushion",
        description: "Memory foam ergonomic back cushion with cooling gel layer.",
        category: "Accessories",
        price: 299,
        stock: 50,
        attributes: { material: "Memory Foam", washableCover: true },
        deliveryDays: 2,
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "prod-105",
        merchantId: "ergospace",
        name: "Monitor Arm Dual Gas",
        description: "Gas spring dual monitor arm supporting up to 32 inch displays.",
        category: "Accessories",
        price: 499,
        stock: 20,
        attributes: { maxWeightKg: 12, VESA: "75x75/100x100" },
        deliveryDays: 2,
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },

  // 2. DeskForge (Heavy-Duty Height Adjustable Standing Desks)
  {
    id: "deskforge",
    name: "DeskForge",
    description: "Industrial-grade dual-motor motorized standing desks, solid hardwood workstations, and cable organizers.",
    categories: ["Desks", "Workstations", "Accessories"],
    maxDiscountPercent: 12,
    minimumMarginPercent: 25,
    maxAutoTransactionAmount: 15000,
    approvalRequiredAbove: 12000,
    allowSlowMovingInventoryDiscount: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    initialProducts: [
      {
        id: "df-201",
        merchantId: "deskforge",
        name: "DeskForge Apex Dual-Motor Standing Desk",
        description: "Heavy-duty electric height-adjustable desk with anti-collision gyroscope and 4 presets.",
        category: "Desks",
        price: 3299,
        stock: 18,
        attributes: { widthCm: 140, depthCm: 70, heightRangeCm: "65-128", motorCount: 2 },
        deliveryDays: 4,
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "df-202",
        merchantId: "deskforge",
        name: "DeskForge Solid Oak Studio Desk",
        description: "Continuous grain solid European oak standing desk with integrated power strip.",
        category: "Desks",
        price: 4899,
        stock: 7,
        attributes: { widthCm: 160, depthCm: 80, woodType: "European Oak" },
        deliveryDays: 6,
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "df-203",
        merchantId: "deskforge",
        name: "Under-Desk Magnetic Cable Spine",
        description: "Flexible articulated cable management vertebrae system with weighted base.",
        category: "Accessories",
        price: 249,
        stock: 45,
        attributes: { lengthCm: 130, magneticMount: true },
        deliveryDays: 2,
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "df-204",
        merchantId: "deskforge",
        name: "Anti-Fatigue Active Standing Mat",
        description: "High-density polyurethane calculated standing mat with calculated massage acupressure peaks.",
        category: "Accessories",
        price: 319,
        stock: 30,
        attributes: { thicknessMm: 22, material: "High Density Polyurethane" },
        deliveryDays: 3,
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },

  // 3. OfficePro (Enterprise IT, Conference & Presentation Systems)
  {
    id: "officepro",
    name: "OfficePro",
    description: "Enterprise workspace AV equipment, acoustic privacy pods, conference setups, and conference room boards.",
    categories: ["Conference", "Electronics", "Acoustics"],
    maxDiscountPercent: 10,
    minimumMarginPercent: 18,
    maxAutoTransactionAmount: 15000,
    approvalRequiredAbove: 12000,
    allowSlowMovingInventoryDiscount: false,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    initialProducts: [
      {
        id: "op-301",
        merchantId: "officepro",
        name: "4K AI Conference Soundbar & Auto-Framing Cam",
        description: "All-in-one USB soundbar with 5x zoom 4K AI optical framing and beamforming 6-mic array.",
        category: "Electronics",
        price: 4299,
        stock: 10,
        attributes: { resolution: "4K UHD", micRangeMeters: 6, aiFraming: true },
        deliveryDays: 3,
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "op-302",
        merchantId: "officepro",
        name: "Acoustic Desktop Privacy Divider (Set of 4)",
        description: "PET felt recycled sound-dampening acoustic dividers with universal desk clamps.",
        category: "Acoustics",
        price: 899,
        stock: 22,
        attributes: { nrcRating: 0.85, widthCm: 120, heightCm: 45 },
        deliveryDays: 4,
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "op-303",
        merchantId: "officepro",
        name: "Magnetic Glass Whiteboard Mobile Easel",
        description: "Tempered optical glass double-sided mobile whiteboard with locking caster wheels.",
        category: "Conference",
        price: 1549,
        stock: 14,
        attributes: { boardSizeCm: "120x90", glassType: "Low Iron Tempered" },
        deliveryDays: 5,
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },

  // 4. NordicLiving (IKEA & Scandinavian Minimalist Commercial Furniture)
  {
    id: "nordicliving",
    name: "NordicLiving Commercial",
    description: "Scandinavian minimalist sustainable birch workstations, modular breakroom tables, and natural lighting.",
    categories: ["Desks", "Lighting", "Breakroom"],
    maxDiscountPercent: 18,
    minimumMarginPercent: 15,
    maxAutoTransactionAmount: 15000,
    approvalRequiredAbove: 12000,
    allowSlowMovingInventoryDiscount: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    initialProducts: [
      {
        id: "nl-401",
        merchantId: "nordicliving",
        name: "Stockholm Birch Modular Work Table",
        description: "Sustainably sourced FSC-certified solid birch conference & group work table.",
        category: "Desks",
        price: 1999,
        stock: 16,
        attributes: { seatingCapacity: 6, lengthCm: 200, widthCm: 90 },
        deliveryDays: 4,
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "nl-402",
        merchantId: "nordicliving",
        name: "Fjord Circadian LED Desk Light Bar",
        description: "Ultra-wide glare-free desk lamp with automatic ambient light sensor and color temp adjustment.",
        category: "Lighting",
        price: 549,
        stock: 35,
        attributes: { cri: 98, maxLumens: 1200, kelvinRange: "2700K-6500K" },
        deliveryDays: 2,
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "nl-403",
        merchantId: "nordicliving",
        name: "Oslo Ergonomic Stool (Active Wobble)",
        description: "Core-strengthening dynamic active sitting perch stool with non-slip weighted silicone base.",
        category: "Seating",
        price: 799,
        stock: 28,
        attributes: { heightAdjustable: true, tiltDegrees: 15 },
        deliveryDays: 3,
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },

  // 5. CyberTech Workspaces (Developer Tech Setups & Server Hubs)
  {
    id: "cybertech",
    name: "CyberTech Workspace",
    description: "High-spec developer battlestation equipment, high-wattage GaN charging hubs, and ergonomic keyboards.",
    categories: ["Electronics", "Accessories", "Seating"],
    maxDiscountPercent: 8,
    minimumMarginPercent: 22,
    maxAutoTransactionAmount: 15000,
    approvalRequiredAbove: 12000,
    allowSlowMovingInventoryDiscount: false,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    initialProducts: [
      {
        id: "ct-501",
        merchantId: "cybertech",
        name: "16-in-1 Thunderbolt 4 Enterprise Docking Station",
        description: "Quad-display 4K@60Hz 140W PD laptop docking hub with 2.5Gbps Ethernet and SD 4.0.",
        category: "Electronics",
        price: 1899,
        stock: 19,
        attributes: { portsCount: 16, maxPowerWattage: 140, displayOutputs: 4 },
        deliveryDays: 2,
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "ct-502",
        merchantId: "cybertech",
        name: "CyberSplit Split Ergonomic Mechanical Keyboard",
        description: "Ortholinear hot-swappable split keyboard with programmable OLED displays and tenting kit.",
        category: "Accessories",
        price: 1649,
        stock: 11,
        attributes: { switchType: "Gateron Brown", layout: "Split Ortholinear", bluetooth5: true },
        deliveryDays: 3,
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "ct-503",
        merchantId: "cybertech",
        name: "Apex Gaming & Code Executive Recliner",
        description: "High-resilience cold cure foam seat with carbon-fiber reinforced steel skeleton.",
        category: "Seating",
        price: 2999,
        stock: 8,
        attributes: { reclineDegrees: 165, armrests: "4D Carbon", lumbar: "Integrated Mechanical" },
        deliveryDays: 4,
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
];

// Single export for backwards compatibility
export const DEMO_MERCHANT_ID = "ergospace";
export const DEMO_MERCHANT = DEMO_MERCHANTS[0];
export const DEMO_PRODUCTS = DEMO_MERCHANTS[0].initialProducts;
